name: Daily Regression Suite

on:
  schedule:
    - cron: "20 10 * * *"   # 3:50 PM IST
  workflow_dispatch:

jobs:
  regression-tests:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        playwright install --with-deps
        pip install pytest pytest-html playwright python-dotenv
        playwright install

    - name: Run Regression Tests
      env:
        ERP_USER: ${{ secrets.ERP_USER }}
        ERP_PASS: ${{ secrets.ERP_PASS }}
      run: |
        pytest -s -m picklist
         

    - name: Upload Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: regression-report
        path: reports/

    - name: Upload Screenshots
      uses: actions/upload-artifact@v4
      with:
        name: debug-screenshots
        path: reports/
